[build]
  publish = "dist"    # Tell Netlify to publish from the dist/ folder
  command = "npm run build"  # Build the Vite project before deployment

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[headers]]
  for = "/*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
